# Generated by Django 4.2.1 on 2026-01-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsr', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('software_engineer', 'Software Developer'), ('data_scientist', 'Data Scientist'), ('product_manager', 'Product Manager')], default='software_engineer', max_length=64),
        ),
        migrations.AddField(
            model_name='job',
            name='governorate',
            field=models.CharField(blank=True, choices=[('tunis', 'Tunis'), ('bizerte', 'Bizerte')], max_length=64),
        ),
        migrations.AddField(
            model_name='job',
            name='max_experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
