# Generated by Django 4.2.1 on 2026-01-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsr', '0003_job_category_job_governorate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
